[package]
name = "sonicprobe-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
sonicprobe-core = { path = "../sonicprobe-core" }
claxon = "0.4.3"

[[bin]]
name = "sonicprobe"
path = "src/main.rs"
